export const genrePop = {
  "Point-and-click": 0,
  Fighting: 0,
  Shooter: 0,
  Music: 0,
  Platform: 0,
  Puzzle: 0,
  Racing: 0,
  "Real Time Strategy (RTS)": 0,
  "Role-playing (RPG)": 0,
  Simulator: 0,
  Sport: 0,
  Strategy: 0,
  "Turn-based strategy (TBS)": 0,
  Tactical: 0,
  "Hack and slash/Beat 'em up": 0,
  "Quiz/Trivia": 0,
  Pinball: 0,
  Adventure: 0,
  Indie: 0,
  Arcade: 0,
  "Visual Novel": 0,
  "Card & Board Game": 0,
  MOBA: 0,
};
